<a href="https://colab.research.google.com/github/UchihaItachi95/ML-Algorithms/blob/numPy-important-methods/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
## The numpy library is core library for scientific computing in Python it provides a high-performance multidimensionalarray object and tools for working with these arrays

To use it you can use pip install numpy to install it in your IDE or you can use !pip install in jupyter notebook

In [ ]:
import numpy as np


# Creating Arrays

In [ ]:
a = np.array([1, 2, 3]) # Creating array of 1 dimension
a

array([1, 2, 3])

In [ ]:
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float ) # Creating 2D array with data type float
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
# Creating 3D array of shape (2, 2, 3) that means 2 matrices each one of them has a 2 rows and 3 columns
c = np.array([[(1.5, 2, 3), (4, 5, 6)],[(3, 2, 1), (4, 5, 6)]] ,dtype = float)
print(c)
print(c.shape)


[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]
(2, 2, 3)


# Some helper methods

np.zeros()

In [ ]:
np.zeros((3, 4)) # Create an array of zeros of dimensions (3,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

np.ones()

In [ ]:
np.ones((2, 3, 4),dtype=np.int16) # Create an array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

np.arange()

In [ ]:
d = np.arange(10, 25, 5) # Create an array of evenly spaced values (step value)
# in other words This creates an array of values between 10 and 25, with a step
d

array([10, 15, 20])

np.linspace()

In [ ]:
np.linspace(0, 2, 9) # This creates an array of 9 values between 0 and 2, with a step size of 1/9.

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

np.full()

In [ ]:
e = np.full((2,2), 7) # Creates a constant array of the element 7
e

array([[7, 7],
       [7, 7]])

np.eye()

In [ ]:
f = np.eye(2)# Create a 2x2 identity matrix
f

array([[1., 0.],
       [0., 1.]])

np.random.random()

In [ ]:
np.random.random((2,2)) # Create an array with random values

array([[0.23634864, 0.61444561],
       [0.24545221, 0.70503705]])

np.info()

In [ ]:
np.info(np.ndarray.dtype) # Asking for a help use np.info

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


# Inspecting Your Array

shape

In [ ]:
a.shape # gives you array dimensions

(3,)

len()

In [ ]:
len(a) # Length of array

3

ndim

In [ ]:
b.ndim # Number od array dimension

2

size

In [ ]:
e.size #Number of array elements

4

dtype

In [ ]:
b.dtype  #Data type of array elements

dtype('float64')

dtype.name

In [ ]:
b.dtype.name  #Name of data type

'float64'

astype()

In [ ]:
b.astype(int) #Convert an array to a different type

array([[1, 2, 3],
       [4, 5, 6]])

# Data Types
## np.int64 : Signed 64-bit integer types
## np.float32 : Standard double-precision floating point
## np.complex Complex numbers represented by 128 floats
## np.bool : Boolean type storing TRUE and FALSE values
## np.object : Python object type
## np.string_ Fixed-length string type
## np.unicode_ Fixed-length unicode type


# **Array Mathematics**
Arithmetic Operations


np.subtract()

In [ ]:
g = a - b
np.subtract(a,b) #Subtraction

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

np.add()

In [ ]:
np.add(b,a) #Addition

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

np.divide()

In [ ]:
np.divide(a,b) #Division

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

np.multiply()

In [ ]:
np.multiply(a,b) #Multiplication

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

np.exp()

In [ ]:
np.exp(b) #Exponentiation

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

np.sqrt()

In [ ]:
np.sqrt(b) #Square root

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

np.sin()

In [ ]:
np.sin(a)  #Print sines of an array

array([0.84147098, 0.90929743, 0.14112001])

np.cos()

In [ ]:
np.cos(b) #Elementwise cosine

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

np.log()

In [ ]:
np.log(a)#Elementwise natural logarithm

array([0.        , 0.69314718, 1.09861229])

e.dot()

In [ ]:
e.dot(f) #Dot product

array([[7., 7.],
       [7., 7.]])

## Comparison

In [ ]:
a == b #Elementwise comparison

array([[False,  True,  True],
       [False, False, False]])

In [ ]:
a< 2 #Elementwise comparison

array([ True, False, False])

np.array_equal()

In [ ]:
np.array_equal(a, b) #Arraywise comparison

False

# Subsetting, Slicing, Indexing
## Subsetting

In [ ]:
print(a[2]) #Select the element at the 2nd index

print(b[1,2]) #Select the element at row 1 column 2(equivalent to b[1][2])


3
6.0


## Slicing

In [ ]:
a[0:2]#Select items at index 0 and 1

array([1, 2])

In [ ]:
b[0:2,1] #Select items at rows 0 and 1 in column 1

array([2., 5.])

In [ ]:
b[:1] #Select all items at row0(equivalent to b[0:1, :])

array([[1.5, 2. , 3. ]])

In [ ]:
c[1,...] #Same as[1,:,:]

array([[3., 2., 3.],
       [4., 5., 6.]])

In [ ]:
a[ : : -1] #Reversed array a array([3, 2, 1])

array([3, 2, 1])

## Indexing

In [ ]:
a[a<2] #Select elements from a less than 2

array([1])

## Fancy Indexing

In [ ]:
b[[1,0,1, 0],[0,1, 2, 0]] #Select elements(1,0),(0,1),(1,2) and(0,0)

array([4. , 2. , 6. , 1.5])

In [ ]:
b[[1,0,1, 0]][:,[0,1,2,0]] #Select a subset of the matrix’s rows and columns

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

# Array Manipulation
Transposing Array

In [ ]:
i = np.transpose(b) #Permute array dimensions
i.T #Permute array dimensions (another way to do transpose)

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

Changing Array Shape

In [ ]:
b.ravel() #Flatten the array
g.reshape(3, -2) #Reshape, but don’t change data

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

Adding/Removing Elements

In [ ]:
h = a.copy() # Create a deep copy of the array
h.resize((2,6)) #Return a new arraywith shape(2,6)
h

array([[1, 2, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
np.append(h,g) #Append items to an array

array([ 1. ,  2. ,  3. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [ ]:
np.insert(a,1,5)  #Insert items in an array

array([1, 5, 2, 3])

In [ ]:
np.delete(a,[1])  #Delete items from an array

array([1, 3])